- name: Install nginx
  hosts: web
  become: yes
  tasks:
  - name: nginx
    ansible.builtin.yum:
     name: nginx
     state: installed
  - name: start and enable nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes 